site_name: Opsbox Docs

nav:
  - Welcome! : index.md
  - Core:
    - Home: core/index.md
    - Getting Started:
        - Installation: core/getting_started/installation.md 
        - Running OpsBox: core/getting_started/running.md
        - Plugin Overview: core/plugins/plugin_overview.md
        - Contributing: core/contributing.md
    - Making Plugins:
        - Basics: core/plugins/development_basics.md
        - Making Handlers: core/plugins/making_handlers.md
        - Making Providers: core/plugins/making_providers.md
        - Making Outputs: core/plugins/making_outputs.md
        - Making Checks: core/plugins/making_checks.md
    - Testing:
        - Testing OpsBox: core/testing/testing.md
        - Testing Handlers: core/testing/testing_handlers.md
        - Testing General Plugins: core/testing/testing_general_plugins.md
        - Testing Rego Plugins: core/testing/testing_rego_plugins.md
  - Community Plugins:
    - Home: plugins/index.md
    - AWS:
        - "EC2": 
          - "EC2 Provider":
            - "EC2 provider": plugins/ec2/ec2_provider/ec2_provider.md
          - "EC2 Checks":
            - "Old Snapshots": plugins/ec2/ec2_old_snapshots.md
            - "Stray Instances": plugins/ec2/stray_instances.md
            - "Unattached EIPs": plugins/ec2/unattached_eips.md
            - "Idle Instances": plugins/ec2/idle_instances.md
            - "Stray EBS Volumes": plugins/ec2/stray_ebs.md
        - "S3":
          - "Amazon S3 Provider":
            - "S3 provider": plugins/s3/s3_provider/s3_provider.md
          - "Amazon S3 Checks":
            - "Unused Buckets": plugins/s3/unused_buckets.md
            - "Storage Class usage": plugins/s3/storage_class_usage.md
            - "Object Last Modified": plugins/s3/object_last_modified.md
        - "RDS":
          - "Amazon RDS Provider":
            - "RDS provider": plugins/rds/rds_provider/rds_provider.md
          - "Amazon RDS Checks":
            - "RDS Idle": plugins/rds/rds_idle.md
            - "Old Snapshots": plugins/rds/old_snapshots.md
            - "Empty Storage": plugins/rds/empty_storage.md
        - "IAM":
          - "Amazon IAM Provider":
            - "IAM provider": plugins/iam/iam_provider/iam_provider.md
          - "Amazon IAM Checks":
            - "Console Access": plugins/iam/console_access.md
            - "Unused Policies": plugins/iam/unused_policies.md
            - "MFA Enabled": plugins/iam/mfa_enabled.md
            - "Overdue Api Keys": plugins/iam/overdue_api_keys.md
        - "ELB":
          - "Amazon ELB Provider":
            - "ELB provider": plugins/elb/elb_provider/elb_provider.md
          - "Amazon ELB Checks":
            - "High Error Rate Load Balancers": plugins/elb/high_error_rate.md
            - "Inactive Load Balancers": plugins/elb/inactive_load_balancers.md
            - "Low Request Count Load Balancers": plugins/elb/low_request_counts.md

        - "R53":
          - "Amazon R53 Provider":
            - "R53 provider": plugins/r53/r53_provider/r53_provider.md
          - "Amazon R53 Checks":
            - "Empty Zones": plugins/r53/empty_zones.md
    - Outputs:
        - "Slack Output": plugins/outputs/slack.md
        - "Cli Output": plugins/outputs/cli.md
        - "Email Output": plugins/outputs/email.md
        - "Jira Output": plugins/outputs/jira.md
        - "Pagerduty Output": plugins/outputs/pagerduty.md
        - "Azure Output": plugins/outputs/azure.md
        - "Github Output": plugins/outputs/github.md
        - "Text File Output": plugins/outputs/text.md
        - "Json File Output": plugins/outputs/json.md

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences